zoo/zoo/Controllers/CaregiverSuperAttractionController.cs
using zoo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections;

namespace zoo.Controllers
{
    public class CaregiverSuperAttractionController : Controller
    {
        // GET: CaregiverSuperAttraction
        public ActionResult AddAttraction()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAttraction(Attraction Model, DateTime from, DateTime to, TimeSpan Tfrom, TimeSpan Tto, decimal cost, int amount)
        {
            
            using (team4zooEntities db = new team4zooEntities())
            {
                Guid ID = System.Guid.NewGuid();
                var key = ID;
                Attraction NewEntry = new Attraction();
                NewEntry.manager_ID = (System.Guid)Session["Employee_ID"];
                NewEntry.attraction_name = Model.attraction_name;
                NewEntry.start_date = from;
                NewEntry.end_date = to;
                NewEntry.start_time = Tfrom;
                NewEntry.end_time = Tto;
                NewEntry.isActive = true;
                NewEntry.Attraction_ID = key; 
                db.Attractions.Add(NewEntry);
                db.SaveChanges();
                ViewBag.Message = "Attraction Added";

                Guid dept = new Guid("7203f98e-e4dc-4edd-b221-98b5855fd4e3");
                Inventory Ticket = new Inventory();
                Ticket.Item_ID = key;
                Ticket.item_name = Model.attraction_name;
                Ticket.last_ordered = from;
                Ticket.price = cost;
                Ticket.ordered_quantity = amount;
                Ticket.Department_ID = dept;
                db.Inventory.Add(Ticket);
                db.SaveChanges();
            }
                return View();
        }
        public ActionResult ViewAttractions()
        {
            team4zooEntities db = new team4zooEntities();

            List<Attraction> attractionlist = db.Attractions.ToList();
            List<Attraction> SortedAttractions = attractionlist.OrderBy(x => x.start_date).ToList();
            return View(SortedAttractions);
        }
    }
}

zoo/zoo/Views/CaregiverSuperAttraction/AddAttraction.cshtml
@using zoo.Models
@model Attraction
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head runat="server">
    <meta name="viewport" content="width=device-width" />
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <style>
        #login-div {
            position: absolute;
            left: 37%;
            top: 40%;
            border: 1px solid #ccc;
            padding: 10px 10px;
            background-color: white;
        }

        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body style="background-color:khaki">
    <header style="font-size:3vw; margin-top:50px">
        <text style="align-content:center"> Add Attraction</text>
    </header>
    <div id="login-div">
        @using (Html.BeginForm("AddAttraction", "CaregiverSuperAttraction", FormMethod.Post))
        {
            <table>
                <tr>
                    <td></td>
                    <td style="text-align:center">Create Attraction</td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.attraction_name)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.attraction_name)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Start Date</b>
                    </td>
                    <td>
                        <input type="date" name="from" id="from">
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>End Date</b>
                    </td>
                    <td>
                        <input type="date" name="to" id="to">
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Start Time</b>
                    </td>
                    <td>
                        <input type="time" name="Tfrom" id="Tfrom">
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>End Time</b>
                    </td>
                    <td>
                        <input type="time" name="Tto" id="Tto">
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Ticket Price</b>
                    </td>
                    <td>
                        <input type="text" name="cost" id="cost">
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Tickets to Order</b>
                    </td>
                    <td>
                        <input type="text" name="amount" id="amount">
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="Submit" name="name" value="Submit" />
                        <input type="reset" name="name" value="Clear" />
                    </td>
                </tr>
            </table>
        }
        @if (ViewBag.Message != null)
        {
            <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };

            </script>
        }
    </div>
</body>
</html>

zoo/zoo/Views/CaregiverSuperAttraction/ViewAttractions.cshtml
@model IEnumerable<zoo.Models.Attraction>

@{
    ViewBag.Title = "ViewInventory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html lang="en">
<title>Attractions</title>
<head>
    @*<title>SalesManager Home</title>*@
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <style>
        .collapsible {
            background-color: #4E4D4D;
            color: white;
            cursor: pointer;
            padding: 18px;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 15px;
        }

            .active, .collapsible:hover {
                background-color: #555;
            }

        .content {
            padding: 0 18px;
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.2s ease-out;
            background-color: #f1f1f1;
        }

        .collapsible:after {
            content: '\02795'; /* Unicode character for "plus" sign (+) */
            font-size: 13px;
            color: white;
            float: right;
            margin-left: 5px;
        }

        .active:after {
            content: "\2796"; /* Unicode character for "minus" sign (-) */
        }
    </style>
</head>
<h2>ViewInventory</h2>
<body>
    <button class="collapsible">Attractions</button>
    <div class="content">
        <table class="table">
            <tr>
                <th>
                    @Html.Label("Attraction Name")
                </th>
                <th>
                    @Html.Label("Start Date")
                </th>
                <th>
                    @Html.Label("End Date")
                </th>
                <th>
                    @Html.Label("Start Time")
                </th>
                <th>
                    @Html.Label("End Time")
                </th>

                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.attraction_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.start_date)
                    </td>
                     <td>
                        @Html.DisplayFor(modelItem => item.end_date)
                    </td>
                     <td>
                        @Html.DisplayFor(modelItem => item.start_time)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.end_time)
                    </td>
                    @*@<td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Item_ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Item_ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Item_ID })
                    </td>*@
                </tr>
            }

        </table>
    </div>


    <script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function () {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.maxHeight) {
            content.style.maxHeight = null;
        } else {
            content.style.maxHeight = content.scrollHeight + "px";
        }
    });
}
    </script>
</body>