zoo/zoo/Models/Inventory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace zoo.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Inventory
{

    public Inventory()
    {

        this.Shop_Sale_Record = new HashSet<Shop_Sale_Record>();

    }


    public System.Guid Item_ID { get; set; }
        [DisplayName("Item Name")]
        public string item_name { get; set; }

    public System.DateTime last_ordered { get; set; }

    public Nullable<System.DateTime> resupply_date { get; set; }

    public decimal price { get; set; }
        [DisplayName("Quantity")]
        public int ordered_quantity { get; set; }

    public System.Guid Department_ID { get; set; }

    public decimal wholesaleprice { get; set; }



    public virtual ICollection<Shop_Sale_Record> Shop_Sale_Record { get; set; }

}

}

zoo/zoo/Models/Shop.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.Shop_Sale_Record = new HashSet<Shop_Sale_Record>();
        }
    
        public System.Guid Shop_ID { get; set; }
        public string shop_loc { get; set; }
        public string shop_name { get; set; }
        public System.Guid Manager_Employee_ID { get; set; }
        public System.Guid Department_ID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Shop_Sale_Record> Shop_Sale_Record { get; set; }
    }
}

zoo/zoo/Controllers/InventoryController.cs
using zoo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections;

namespace zoo.Controllers
{
    public class InventoryController : Controller
    {
        // GET: CaregiverSuperAttraction
        public ActionResult AddItem()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddItem(Inventory Model, DateTime? last, DateTime? re)
        {

             using (team4zooEntities db = new team4zooEntities())
            {
                DateTime date = default(DateTime);
                if (last.HasValue)
                    date = last.Value;               
                try
                {
                    Guid ID = System.Guid.NewGuid();
                    Guid dept = new Guid("56320bbb-5776-42cc-8fac-42e648ec8719");
                    Inventory Item = new Inventory();
                    Item.Item_ID = ID;
                    Item.item_name = Model.item_name;
                    Item.last_ordered = date;
                    Item.resupply_date = re;
                    Item.price = Model.price;
                    Item.ordered_quantity = Model.ordered_quantity;
                    Item.Department_ID = dept;
                    Item.wholesaleprice = Model.wholesaleprice;
                    db.Inventory.Add(Item);
                    db.SaveChanges();
                }
                catch(Exception)
                {
                    ViewBag.Message = "All Fields Except Resupply Date Are Required";
                    return View();
                }

            }

            ViewBag.Message = "Item Added";
            return View();
        }
    }
}

zoo/zoo/Controllers/SalesManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using Newtonsoft.Json;
using System.Data.SqlTypes;
using zoo.Models;

namespace zoo.Controllers
{
    public class SalesManagerController : Controller
    {
        // GET: SalesManager
        public ActionResult Index()
        {
            IEnumerable<Employee> EmployeeList = ViewMyEmployees();
            List<MyEmployee> Employees = new List<MyEmployee>();
            foreach (var person in EmployeeList)
            {
                Employees.Add(new MyEmployee(person.f_name, person.l_name, person.email, person.phone_num));
            }
            return View(Employees);
        }

        public ActionResult Item()
        {
            using (team4zooEntities DB = new team4zooEntities())
            {
                List<Inventory> itemlist = DB.Inventory.ToList();

                return View(itemlist);
            }
        }

        public IEnumerable<Employee> ViewMyEmployees()
        {
            using (team4zooEntities db = new team4zooEntities())
            {
                System.Guid MyEmployee_ID = (System.Guid)Session["Employee_ID"];
                return db.Employees.ToList().Where(x => (x.Supervisor_ID == MyEmployee_ID));
            }
        }
        public ActionResult Login()
        {
            return RedirectToAction("Index", "Login");
        }

        public ActionResult Inventory()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Contact(Employee Model)
        {
            using (team4zooEntities db = new team4zooEntities())
            {
                var Phone = db.Employees.Where(x => x.f_name == Model.f_name && x.l_name == Model.l_name).Select(y => y.phone_num).FirstOrDefault();
                var Email = db.Employees.Where(x => x.f_name == Model.f_name && x.l_name == Model.l_name).Select(y => y.email).FirstOrDefault();
                String contactInfo = " Phone: " + Phone + " " + ", " + " Email: " + Email;
                if (Phone != null && Email != null)
                    ViewBag.Message = contactInfo;
                else
                    ViewBag.Message = "No one by that name was found";
                return View();
            }
        }

        [HttpPost]
        public ActionResult Inventory(Inventory Model)
        {
            using (team4zooEntities db = new team4zooEntities())
            {
                var Price = db.Inventory.Where(x => x.item_name == Model.item_name).Select(y => y.price).FirstOrDefault();
                var InStock = db.Inventory.Where(x => x.item_name == Model.item_name).Select(y => y.ordered_quantity).FirstOrDefault();
                var ItemName = db.Inventory.Where(x => x.item_name == Model.item_name).Select(y => y.item_name).FirstOrDefault();

                String ItemInfo = ItemName + " Price: " + Price + " " + ", " + " In Stock: " + InStock;
                if (ItemName != null)
                    ViewBag.Message = ItemInfo;
                else
                    ViewBag.Message = "No Item Found";
                return View();
            }
        }

        public ActionResult Shop()
        {
            team4zooEntities DB = new team4zooEntities();

            List<Shop> shoplist = DB.Shops.ToList();
            return View(shoplist);
        }

        public ActionResult ViewInventory()
        {
            team4zooEntities db = new team4zooEntities();
            
            List<Inventory> inventorylist = db.Inventory.ToList();
            return View(inventorylist);
        }

        [HttpGet]
        public ActionResult editItem(string id)
        {
            using (team4zooEntities DB = new team4zooEntities())
            {
                Guid ID = new Guid(id);
                Inventory item = DB.Inventory.Single(Inventory => Inventory.Item_ID == ID);

                return View(item);
            }
        }

        //This creates a SQL ready item object and adds to database
        public void SaveItem(Inventory item)
        {
            using (SqlConnection conn = new SqlConnection())
            {
                conn.ConnectionString = "Server=den1.mssql8.gear.host;Database=team4zoo;Uid=team4zoo;Pwd=Ji627i1J-x5?"; //Connection String with login info.

                //Call Query
                SqlCommand cmd = new SqlCommand("SaveItem", conn);
                cmd.CommandType = CommandType.StoredProcedure;

                //Set Parameters
                SqlParameter paramIName = new SqlParameter();//ItemName
                paramIName.ParameterName = "@item_name";
                paramIName.Value = item.item_name;
                cmd.Parameters.Add(paramIName);

                SqlParameter paramID = new SqlParameter();//ItemID
                paramID.ParameterName = "@Item_ID";
                paramID.Value = item.Item_ID;
                cmd.Parameters.Add(paramID);

                SqlParameter paramPrice = new SqlParameter();//Price
                paramPrice.ParameterName = "@price";
                paramPrice.Value = item.price;
                cmd.Parameters.Add(paramPrice);

                SqlParameter paramQuantity = new SqlParameter();//Quantity
                paramQuantity.ParameterName = "@ordered_quantity";
                paramQuantity.Value = item.ordered_quantity;
                cmd.Parameters.Add(paramQuantity);

                SqlParameter paramWPrice = new SqlParameter(); //Wholesale Price
                paramWPrice.ParameterName = "@wholesaleprice";
                paramWPrice.Value = item.wholesaleprice;
                cmd.Parameters.Add(paramWPrice);


                conn.Open(); //Opens connection
                cmd.ExecuteNonQuery(); //Add to table
            }
        }

        [HttpPost]
        public ActionResult editItem(Inventory item)
        {

            if (ModelState.IsValid && item.item_name.Length > 0 && item.price >= 0 && item.ordered_quantity >= 0 && item.wholesaleprice >= 0)
            {
                SalesManagerController salesmController = new SalesManagerController();

                salesmController.SaveItem(item);

                ViewBag.Message = "Edit Successful";

                return RedirectToAction("ViewInventory");
            }
            else
            {
                ViewBag.Message = "Invalid Input";
                return View();
            }
        }

        //DeleteItem Method
        public void DeleteInventory(Guid id)
        {
            using (SqlConnection conn = new SqlConnection())
            {
                conn.ConnectionString = "Server=den1.mssql8.gear.host;Database=team4zoo;Uid=team4zoo;Pwd=Ji627i1J-x5?"; //Connection String with login info.

                //Call Query
                SqlCommand cmd = new SqlCommand("DeleteInventory", conn);
                cmd.CommandType = CommandType.StoredProcedure;

                //Set Parameters
                SqlParameter paramID = new SqlParameter();//ItemName
                paramID.ParameterName = "@Item_ID";
                paramID.Value = id;
                cmd.Parameters.Add(paramID);

                conn.Open(); //Opens connection
                cmd.ExecuteNonQuery(); //Add to table
            }
        }

        [HttpPost]
        public ActionResult DeleteItem(string id)
        {
            Guid guid = new Guid(id);
            DeleteInventory(guid);
            return RedirectToAction("ViewInventory");
        }


    }
}

zoo/zoo/Views/SalesManager/Contact.cshtml
@using zoo.Models
@model Employee

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head runat="server">
    <meta name="viewport" content="width=device-width" />
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <style>
        #login-div {
            position: absolute;
            left: 37%;
            top: 40%;
            border: 1px solid #ccc;
            padding: 10px 10px;
            background-color: white;
        }

        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body style="background-color:cornflowerblue">
    <header style="font-size:3vw;">
        <text style="align-content:center"> Contact Lookup</text>
    </header>
    <div id="login-div">
        @using (Html.BeginForm("Contact", "SalesManager", FormMethod.Post))
        {
            <table>
                <tr>
                    <td></td>
                    <td style="text-align:center">Check For</td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.f_name)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.f_name)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.f_name)</td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.l_name)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.l_name)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="Submit" name="name" value="Submit" />
                        <input type="reset" name="name" value="Clear" />
                    </td>
                </tr>
            </table>

        }
        @if (ViewBag.Message != null)
        {
            <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };

            </script>
        }
    </div>
</body>
</html>

zoo/zoo/Views/SalesManager/Index.cshtml
@{
    /**/

    Layout = "~/Views/Shared/_Layout.cshtml";

}
@using zoo.Models
@model List<MyEmployee>

<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }

        th {
            background-color: #4CAF50;
            color: white;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <a class="weatherwidget-io" href="https://forecast7.com/en/29d76n95d37/houston/" data-label_1="HOUSTON" data-label_2="WEATHER" data-theme="original">HOUSTON WEATHER</a>
            <script>
                !function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = 'https://weatherwidget.io/js/widget.min.js'; fjs.parentNode.insertBefore(js, fjs); } }(document, 'script', 'weatherwidget-io-js');
            </script>
        </div>
    </div>
    <div class="container">
        <h2>Employees</h2>
        <table>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.FullName</td>
                    <td>@item.email</td>
                    <td>@item.phone</td>
                </tr>
            }
        </table>
    </div>

</body>
</html>

zoo/zoo/Views/SalesManager/Inventory.cshtml
@using zoo.Models
@model Inventory
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head runat="server">
    <meta name="viewport" content="width=device-width" />
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <style>
        #login-div {
            position: absolute;
            left: 37%;
            top: 40%;
            border: 1px solid #ccc;
            padding: 10px 10px;
            background-color: white;
        }

        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body style="background-color:cornflowerblue">
    <header style="font-size:3vw;">
        <text style="align-content:center"> Check Inventory</text>
    </header>
    <div id="login-div">
        @using (Html.BeginForm("Inventory", "SalesManager", FormMethod.Post))
        {
            <table>
                <tr>
                    <td></td>
                    <td style="text-align:center">Check For</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.item_name)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.item_name)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="Submit" name="name" value="Submit" />
                        <input type="reset" name="name" value="Clear" />
                    </td>
                </tr>
            </table>
        }

        @if (ViewBag.Message != null)
        {
            <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };

            </script>
        }
    </div>
</body>
</html>

zoo/zoo/Views/SalesManager/Shop.cshtml
@model IEnumerable<zoo.Models.Shop>

@{
    ViewBag.Title = "Shop";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <html lang="en">
        <title>Shops</title>
<head>
    <title>SalesManager Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<style>
.collapsible {
    background-color: #4E4D4D;
    color: white;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
}

.active, .collapsible:hover {
    background-color: #555;
}

.content {
    padding: 0 18px;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
    background-color: #f1f1f1;
}

.collapsible:after {
    content: '\02795'; /* Unicode character for "plus" sign (+) */
    font-size: 13px;
    color: white;
    float: right;
    margin-left: 5px;
}

.active:after {
    content: "\2796"; /* Unicode character for "minus" sign (-) */
}
</style>
</head>
<h2>Shop</h2>
<body>
    <button class="collapsible">Shops</button>
    <div class="content">
        <table class="table">
            <tr>
                <th>
                    @Html.Label("Shop Name")
                </th>
                <th>
                    @Html.Label("Shop Location")
                </th>
                <th>
                    @Html.Label("Supervisor ID")
                </th>

                <th></th>
            </tr>

@foreach (var item in Model){
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.shop_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.shop_loc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Manager_Employee_ID)
        </td>
    </tr>
}

</table>
    </div>


<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function () {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.maxHeight) {
            content.style.maxHeight = null;
        } else {
            content.style.maxHeight = content.scrollHeight + "px";
        }
    });
}
</script>
</body>

zoo/zoo/Views/SalesManager/ViewInventory.cshtml
@model IEnumerable<zoo.Models.Inventory>

@{
    ViewBag.Title = "ViewInventory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <html lang="en">
        <title>Inventory</title>
<head>
    <title>SalesManager Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<style>
.collapsible {
    background-color: #4E4D4D;
    color: white;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
}

.active, .collapsible:hover {
    background-color: #555;
}

.content {
    padding: 0 18px;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
    background-color: #f1f1f1;
}

.collapsible:after {
    content: '\02795'; /* Unicode character for "plus" sign (+) */
    font-size: 13px;
    color: white;
    float: right;
    margin-left: 5px;
}

.active:after {
    content: "\2796"; /* Unicode character for "minus" sign (-) */
}
</style>
</head>
<h2>ViewInventory</h2>
<body>
    <button class="collapsible">Inventory</button>
    <div class="content">
        <table class="table">
            <tr>
                <th>
                    @Html.Label("Item Name")
                </th>
                <th>
                    @Html.Label("Price")
                </th>
                <th>
                    @Html.Label("Quantity")
                </th>
                <th>
                    @Html.Label("Wholesale Price")
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.item_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ordered_quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.wholesaleprice)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "editItem", new { id = item.Item_ID }, new { @class = "btn btn-primary" })
                        <p></p>
                        @using (Html.BeginForm("DeleteItem", "SalesManager", new { id = item.Item_ID }))
                        {
                            <input type="submit" value="Delete" class="btn btn-primary" onclick="return confirm('Confirm Delete Item: @item.item_name');" />
                        }
                    </td>
                </tr>
            }

        </table>
    </div>

    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">

            window.onload = function () {
                alert("@ViewBag.Message");
            };
        </script>
    }

    <script>
        var coll = document.getElementsByClassName("collapsible");
        var i;

        for (i = 0; i < coll.length; i++) {
            coll[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var content = this.nextElementSibling;
                if (content.style.maxHeight) {
                    content.style.maxHeight = null;
                } else {
                    content.style.maxHeight = content.scrollHeight + "px";
                }
            });
        }
    </script>
</body>

zoo/zoo/Views/SalesManager/editItem.cshtml
@model zoo.Models.Inventory

@{
    ViewBag.Title = "editItem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>editItem</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Inventory</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.item_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.item_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.item_name, "", new { @class = "text-danger" })
        </div>
    </div>


    @Html.HiddenFor(model => model.Item_ID)

    <div class="form-group">
        @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ordered_quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ordered_quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ordered_quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.wholesaleprice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.wholesaleprice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.wholesaleprice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ViewInventory")
</div>