zoo/zoo/Controllers/CareGiverReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using zoo.Models;

namespace zoo.Controllers
{
    public class CareGiverReportController : Controller
    {
        // GET: CareGiverReport
        public ActionResult Index ()
        {
            List<string> ErrorMsg = new List<string>();
            ErrorMsg.Add(" ");
            IEnumerable<Animal> MyAnimals = ViewMyAnimals();
            var tuple = new Tuple<IEnumerable<Animal>,IEnumerable<string> >(MyAnimals, ErrorMsg);
            return View(tuple);
        }
     
        public IEnumerable<Animal> ViewMyAnimals()
        {
            using (team4zooEntities db = new team4zooEntities())
            {
                System.Guid Employee_ID = (System.Guid)Session["Employee_ID"];
                return db.Animals.ToList().Where(x => (x.Assignee1_ID == Employee_ID || x.Assignee2_ID == Employee_ID || x.Assignee3_ID == Employee_ID));
            }
        }

      
        [HttpPost]
        public ActionResult ViewFoodReport(Animal model, DateTime? from, DateTime? to)
        {
            using (team4zooEntities db = new team4zooEntities())
            {
               System.Guid Animal_ID = db.Animals.Where(x => x.animal_name == model.animal_name).Select(y => y.Animal_ID).FirstOrDefault();
               if(!from.HasValue || !to.HasValue || model.animal_name == null)
                {
                    List<string> ErrorMsg = new List<string>();
                    ErrorMsg.Add("Fill All the Fields!");
                    IEnumerable<Animal> MyAnimals = ViewMyAnimals();
                    var tuple = new Tuple<IEnumerable<Animal>, IEnumerable<string>>(MyAnimals, ErrorMsg);
                    return View("~/Views/CareGiverReport/Index.cshtml", tuple);
                }
                else
                {
               //     IEnumerable<Animal> MyAnimals = ViewMyAnimals();
                    IEnumerable<Animal_Feed_Care> FeedReport = db.Animal_Feed_Care.Where(x => x.Animal_ID == Animal_ID && (x.date >= from || x.date <= to)).ToList();
                    var tuple = new Tuple<IEnumerable<Animal_Feed_Care>>(FeedReport);
                    return View("~/Views/CareGiverReport/Report.cshtml",tuple);
                }

            }
            
        }

        [HttpPost]
        public ActionResult ViewMedicationReport(Animal model, DateTime? from, DateTime? to)
        {
            using (team4zooEntities db = new team4zooEntities())
            {
                System.Guid Animal_ID = db.Animals.Where(x => x.animal_name == model.animal_name).Select(y => y.Animal_ID).FirstOrDefault();
                if (!from.HasValue || !to.HasValue || model.animal_name == null)
                {
                    List<string> ErrorMsg = new List<string>();
                    ErrorMsg.Add("Fill All the Fields!");
                    IEnumerable<Animal> MyAnimals = ViewMyAnimals();
                    var tuple = new Tuple<IEnumerable<Animal>, IEnumerable<string>>(MyAnimals, ErrorMsg);
                    return View("~/Views/CareGiverReport/Index.cshtml", tuple);
                }
                else
                {
                    IEnumerable<Animal_Medication_Care> MedicationReport = db.Animal_Medication_Care.Where(x => x.Animal_ID == Animal_ID && (x.date >= from || x.date <= to)).ToList();
                    var tuple = new Tuple<IEnumerable<Animal_Medication_Care>>(MedicationReport);
                    return View("~/Views/CareGiverReport/MedicationReport.cshtml", tuple);
                }

            }

        }
    }
}

zoo/zoo/Views/CareGiverReport/Index.cshtml
@using zoo.Models
@model Tuple< IEnumerable < Animal >, IEnumerable<string>>

@{
    ViewBag.Title = "Index";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }

        th {
            background-color: #4CAF50;
            color: white;
        }


        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div>
        <table>
            @using (Html.BeginForm("ViewFoodReport", "CareGiverReport", FormMethod.Post))
            {
                <tr><td></td><td></td><td></td><td></td></tr>
                <tr><td></td><td></td><td></td><td></td></tr>
                <tr><td><h3>Food Reports</h3></td><td></td><td></td><td></tr>
                <tr>
                    <th>My Animals</th>
                    <th>From</th>
                    <th>To</th>
                    <th></th>
                </tr>
                <tr><td></td><td></td><td></td><td></td></tr>
                <tr>
                    <td>
                        @Html.DropDownListFor(model => model.Item1.ElementAt(0).animal_name,
                         new SelectList(Model.Item1),
                         "Select Value")
                    </td>

                    <td>
                        <input type="date" name="from" id="from">
                    </td>

                    <td>
                        <input type="date" name="to" id="to">
                    </td>

                    <td>
                        <input type="submit" value="submit" />
                    </td>

                </tr>
            }

            @using (Html.BeginForm("ViewMedicationReport", "CareGiverReport", FormMethod.Post))
            {
                
                <tr><td></td><td></td><td></td><td></td></tr>
                <tr><td><h3>Medication Reports</h3></td><td></td><td></td><td></tr>
                <tr>
                    <th>My Animals</th>
                    <th>From</th>
                    <th>To</th>
                    <th></th>
                </tr>
                <tr><td></td><td></td><td></td><td></td></tr>
                <tr>
                    <td>
                        @Html.DropDownListFor(model => model.Item1.ElementAt(0).animal_name,
                         new SelectList(Model.Item1),
                         "Select Value")
                    </td>

                    <td>
                        <input type="date" name="from" id="from">
                    </td>

                    <td>
                        <input type="date" name="to" id="to">
                    </td>

                    <td>
                        <input type="submit" value="submit" />
                    </td>

                </tr>
            }
        </table>
        <div>
            <label class="field-validation-error">@Html.DisplayFor(model => model.Item2)</label>
        </div>
    </div>
</body>
</html>

zoo/zoo/Views/CareGiverReport/MedicationReport.cshtml
@{
    ViewBag.Title = "MedicationReport";
}

@using zoo.Models
@model Tuple<IEnumerable<Animal_Medication_Care>>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }

        th {
            background-color: #4CAF50;
            color: white;
        }
    </style>>
</head>
<body>
    <div>
        <table>
            
            <tr><td></td><td></td><td></td><td></td></tr>
            <tr><td><h3>Medication Reports</h3></td><td></td><td></td><td></tr>

            <tr>
                <th>Medication</th>
                <th>dose</th>
                <th>Vet</th>
                <th>Description</th>
                <th>Date</th>
                <th>Time</th>
            </tr>
            @foreach (var item in Model.Item1)
            {
            <tr>
                <td>@item.medication</td>
                <td>@item.dose</td>
                <td>@item.vet</td>
                <td>@item.description</td>
                <td>@item.date</td>
                <td>@item.time</td>
            </tr>
            }


        </table>

    </div>
</body>
</html>

zoo/zoo/Views/CareGiverReport/Report.cshtml
@{
    ViewBag.Title = "Report";
}

@using zoo.Models
@model Tuple<IEnumerable<Animal_Feed_Care>>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }

        th {
            background-color: #4CAF50;
            color: white;
        }
    </style>>
</head>
<body>
    <div>
        <table>
                <tr><td></td><td></td><td></td><td></td></tr>
                <tr><td></td><td></td><td></td><td></td></tr>
                <tr><td><h3>Food Reports</h3></td><td></td><td></td><td></tr>
                                
                        <tr>
                            <th>Food Type</th>
                            <th>Quantity in Pounds</th>
                            <th>Date</th>
                            <th>Time</th>
                        </tr>
                        @foreach (var item in Model.Item1)
                        {
                            <tr>
                                <td>@item.food_type</td>
                                <td>@item.quantity_fed</td>
                                <td>@item.date</td>
                                <td>@item.time</td>
                            </tr>
                        }
                   
            
        </table>

    </div>
</body>
</html>